version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout  # This is the checkout step

      - run:
          name: Run Tests
          command: |
            python --version
            - run: python tests.py
