version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout 
      - run:
          name: Run build
            python --version
            python main.py
  test::
    docker:
      - image: circleci/python:3.8
      - run:  
        name: Run Test
          python tests.py

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
     
